### ISSUE TITLE
FR: spaces as dots rather than outline bullet 

### ISSUE THREAD

**Issue by apolaine** [joethei/obsidian-control-characters#4]
I’d love it if the spaces were represented by a small dot the way BBEdit does it rather than the outline circle. It makes it easier to visually pass. I guess the ideal would be able to set the characters in settings somewhere. 

(And thanks for the plug-in!)

**Comment by joethei** [comment]
I just released a version which uses a dot instead of the circle.
(Right after you asked in discord, so you might have installed the older version)

Currently you could change the icon with a bit of css,
but I am already working on making this configurable with the _[Style Settings](https://github.com/mgmeyers/obsidian-style-settings)_ plugin.
(adding this as a setting in my plugin is a bit harder than with the _Style Settings_ plugin)

**Comment by apolaine** [comment]
Brilliant, thank you!



Cheers,

Andy
